FROM golang:1.25.9-alpine3.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -ldflags="-s -w" -o /main ./cmd/lambda

FROM public.ecr.aws/lambda/provided:al2023

COPY --from=builder /main ./main
ENTRYPOINT ["./main"]
