version = 0.1

[default.build.parameters]
template_file = "template.yaml"
cached = true
parallel = true

[default.validate.parameters]
template_file = "template.yaml"
lint = false

[default.deploy.parameters]
stack_name = "opsdesk-dev"
resolve_s3 = true
resolve_image_repos = true
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
template_file = "template.yaml"
parameter_overrides = "ProjectName=\"opsdesk\" StageName=\"dev\" AppEnv=\"dev\" ApiBasePath=\"/v1\" FrontendOrigin=\"https://opsdesk-teal.vercel.app\" LogLevel=\"info\" EnableDynamoPointInTimeRecovery=\"true\""
s3_prefix = "opsdesk-dev"
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
